import React, { useState, useMemo } from 'react';
import { CourseHeader, Section, InfoBlock, TipBanner, InteractiveChecklist, AccordionFAQ, Quiz, Flashcard, BentoGrid, BentoCard, InteractiveExercise } from '../components/SharedUI';
import { useProgress } from '../hooks/useProgress';
import { motion } from 'framer-motion';
import { Table, Hash, HelpCircle, ShieldCheck, Zap } from 'lucide-react';

const ModularStructureSim: React.FC = () => {
  const [n, setN] = useState<number>(5);
  const [operation, setOperation] = useState<'add' | 'mul'>('add');
  const [selectedElement, setSelectedElement] = useState<number>(1);

  // Compute coprime elements for multiplication group of units (Z/nZ)*
  const coprimes = useMemo(() => {
    const list: number[] = [];
    const gcd = (a: number, b: number): number => (b === 0 ? a : gcd(b, a % b));
    for (let i = 1; i < n; i++) {
      if (gcd(i, n) === 1) {
        list.push(i);
      }
    }
    return list;
  }, [n]);

  // Elements currently considered in the algebraic structure
  const elements = useMemo(() => {
    if (operation === 'add') {
      const arr = [];
      for (let i = 0; i < n; i++) arr.push(i);
      return arr;
    } else {
      // Invertible units for multiplication group
      return coprimes;
    }
  }, [n, operation, coprimes]);

  // Compute the subgroup generated by selectedElement
  const generatedSubgroup = useMemo(() => {
    const list: number[] = [];
    if (!elements.includes(selectedElement)) return [];
    
    let current = selectedElement;
    list.push(current);
    
    const limit = 50; // safeguard
    for (let i = 0; i < limit; i++) {
      if (operation === 'add') {
        current = (current + selectedElement) % n;
      } else {
        current = (current * selectedElement) % n;
      }
      if (current === selectedElement || list.includes(current)) break;
      list.push(current);
    }
    // Sort for visual neatness
    return list.slice().sort((a, b) => a - b);
  }, [selectedElement, n, operation, elements]);

  // Compute element order
  const elementOrder = generatedSubgroup.length;

  return (
    <div className="bg-card border-2 border-slate-100 dark:border-slate-800 rounded-3xl p-6 shadow-xl max-w-3xl mx-auto my-8" id="modular-sim-card">
      <h3 className="text-xl font-bold text-center text-slate-800 dark:text-white mb-2 flex items-center justify-center gap-2" id="modular-sim-title">
        <Table className="text-indigo-650" size={22} id="modular-sim-icon" />
        Outil Interactif : Groupes Modulaires {"$\\mathbb{Z}/n\\mathbb{Z}$"}
      </h3>
      <p className="text-xs text-slate-500 text-center mb-6">
        Explorez la structure de groupe abélien en manipulant les lois modulo {"$n$"} et calculez instantanément l'ordre et les sous-groupes engendrés.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-start">
        {/* Controls Panel */}
        <div className="space-y-4" id="modular-controls">
          <div className="bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-4 rounded-xl space-y-4" id="choice-panel">
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest flex items-center gap-1.5" id="choice-hdr">
              <Hash size={12} /> Choix de la structure
            </h4>

            <div>
              <div className="flex justify-between text-xs font-bold mb-1">
                <span className="text-slate-650 dark:text-slate-300">Modulo {"$n$"} :</span>
                <span className="text-indigo-650 font-mono font-black">n = {n}</span>
              </div>
              <input 
                id="modulo-range"
                type="range" min="3" max="11" step="1" value={n} onChange={(e) => {
                  const val = Number(e.target.value);
                  setN(val);
                  setSelectedElement(1);
                }}
                className="w-full h-1.5 bg-slate-200 dark:bg-slate-800 rounded-lg appearance-none cursor-pointer accent-indigo-650"
              />
            </div>

            <div className="space-y-2">
              <span className="block text-xs font-bold text-slate-650 dark:text-slate-300">Loi de composition interne :</span>
              <div className="flex gap-2" id="op-buttons">
                <button
                  id="op-add-btn"
                  onClick={() => {
                    setOperation('add');
                    setSelectedElement(1);
                  }}
                  className={`flex-1 py-1.5 rounded-lg text-xs font-bold border transition-colors ${operation === 'add' ? 'bg-indigo-650 border-indigo-650 text-white shadow-sm' : 'bg-white dark:bg-slate-800 hover:bg-slate-100 border-slate-200 text-slate-600 dark:text-slate-300'}`}
                >
                  Addition (+ mod n)
                </button>
                <button
                  id="op-mul-btn"
                  onClick={() => {
                    setOperation('mul');
                    setSelectedElement(1);
                  }}
                  className={`flex-1 py-1.5 rounded-lg text-xs font-bold border transition-colors ${operation === 'mul' ? 'bg-indigo-650 border-indigo-650 text-white shadow-sm' : 'bg-white dark:bg-slate-800 hover:bg-slate-100 border-slate-200 text-slate-600 dark:text-slate-300'}`}
                >
                  Multiplication (× mod n)
                </button>
              </div>
            </div>

            <div>
              <span className="block text-xs font-bold text-slate-650 dark:text-slate-300 mb-2">Sélectionner un élément :</span>
              <div className="flex flex-wrap gap-1.5" id="el-buttons">
                {elements.map(el => (
                  <button
                    key={el}
                    id={`el-btn-${el}`}
                    onClick={() => setSelectedElement(el)}
                    className={`w-8 h-8 rounded-lg text-xs font-bold border flex items-center justify-center transition-colors ${selectedElement === el ? 'bg-emerald-600 border-emerald-600 text-white' : 'bg-white dark:bg-slate-800 hover:bg-slate-100 border-slate-200 text-slate-650 dark:text-slate-300'}`}
                  >
                    {el}
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-indigo-50/50 dark:bg-indigo-950/25 border border-indigo-100 dark:border-indigo-950 space-y-2 text-xs" id="diag-panel">
            <h4 className="text-xs font-bold text-indigo-800 dark:text-indigo-400 uppercase tracking-wider flex items-center gap-1.5" id="diag-hdr">
              <Zap size={14} /> Diagnostic Algébrique de {"$x = "}{selectedElement} :
            </h4>
            <div className="space-y-1 bg-white/70 dark:bg-black/30 p-2.5 rounded-lg border border-indigo-100/30" id="diag-stats">
              <div className="flex justify-between">
                <span>Groupe étudié :</span>
                <strong className="text-indigo-950 dark:text-indigo-200">
                  {operation === 'add' ? `(ℤ/${n}ℤ, +)` : `((ℤ/${n}ℤ)*, ×)`}
                </strong>
              </div>
              <div className="flex justify-between">
                <span>Ordre du groupe card(G) :</span>
                <strong className="text-indigo-950 dark:text-indigo-200 font-mono">{elements.length}</strong>
              </div>
              <div className="flex justify-between border-t border-slate-100 dark:border-slate-800 pt-1 mt-1 font-semibold text-emerald-700 dark:text-emerald-400">
                <span>Ordre de l'élément o(x) :</span>
                <strong className="font-mono">{elementOrder}</strong>
              </div>
              <div className="flex justify-between">
                <span>Engendré ⟨{selectedElement}⟩ :</span>
                <strong className="font-mono text-emerald-700 dark:text-emerald-400">
                  {`{ ${generatedSubgroup.join(', ')} }`}
                </strong>
              </div>
              <div className="flex justify-between text-[10px] text-slate-400 mt-1">
                <span>Générateur du groupe global ?</span>
                <strong>{elementOrder === elements.length ? 'Oui ✅ (Cyclique)' : 'Non ❌'}</strong>
              </div>
            </div>
            {operation === 'mul' && (
              <p className="text-[10px] text-slate-400 italic">
                Rappel : la loi × n'est un groupe que sur les éléments inversibles (premiers avec {n}).
              </p>
            )}
          </div>
        </div>

        {/* Cayley Table View */}
        <div className="space-y-3" id="cayley-container">
          <span className="block text-xs font-bold text-slate-400 uppercase tracking-wide text-center">
            Table de Cayley (Loi de Composition)
          </span>

          <div className="overflow-auto border border-slate-200 dark:border-slate-800 rounded-xl bg-slate-50 dark:bg-slate-900/50 p-2 max-h-72" id="cayley-scroll">
            <table className="w-full text-center border-collapse" id="cayley-table">
              <thead>
                <tr className="border-b-2 border-slate-300 dark:border-slate-700">
                  <th className="p-1 px-1.5 bg-slate-100 dark:bg-slate-900 font-black text-indigo-650 text-xs">{operation === 'add' ? '+' : '×'}</th>
                  {elements.map(el => (
                    <th key={el} className="p-1 text-xs font-bold text-slate-500 bg-slate-100/50 dark:bg-slate-900/20">{el}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {elements.map(row => {
                  return (
                    <tr key={row} className="border-b border-slate-150 dark:border-slate-850/30">
                      <td className="p-1 bg-slate-100/50 dark:bg-slate-900/20 font-bold text-xs text-slate-500">{row}</td>
                      {elements.map(col => {
                        const cellVal = operation === 'add' ? (row + col) % n : (row * col) % n;
                        const isSubgroupElement = generatedSubgroup.includes(cellVal);
                        
                        return (
                          <td 
                            key={col} 
                            className={`p-1.5 font-mono text-xs transition-colors rounded-sm
                              ${row === col ? 'font-bold' : ''}
                              ${cellVal === selectedElement ? 'bg-amber-100 dark:bg-amber-950/40 text-amber-700 font-extrabold' : ''}
                              ${isSubgroupElement ? 'bg-emerald-50 dark:bg-emerald-950/20 text-emerald-700' : 'text-slate-600 dark:text-slate-400'}
                            `}
                          >
                            {cellVal}
                          </td>
                        );
                      })}
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
          <span className="block text-[10px] text-slate-400 text-center font-mono leading-tight">
            Fond vert : résultats appartenant au sous-groupe engendré. <br />
            Fond beige : emplacements où le résultat équivaut à l'élément {selectedElement}.
          </span>
        </div>
      </div>
    </div>
  );
};

const Course_CPGE_01_Structures_Algebriques: React.FC = () => {
  const { validateCourse } = useProgress();
  const courseId = "/Cours_Math/04_Post_Bac/CPGE/01_CPGE_01_Structures_Algebriques.md";

  const checklistItems = [
    "Maîtriser les axiomes définissant un Groupe, un Anneau et un Corps.",
    "Manipuler les morphismes de groupes (propriété de morphisme, Noyau Ker, Image Im).",
    "Caractériser les sous-groupes stables et appliquer le théorème de Lagrange.",
    "Démontrer qu'une structure modulo n est un corps si et seulement si n est premier.",
    "Calculer l'ordre d'un élément dans un groupe cyclique."
  ];

  return (
    <div className="max-w-4xl mx-auto p-4 md:p-8" id="cpge1-course-root">
      <CourseHeader 
        id="cpge1-header"
        acronym="ALG" 
        title="Structures Algébriques" 
        subtitle="Plongez dans les fondations structurelles de l'algèbre : groupes, anneaux, corps, morphismes, étude axiomatique des ensembles dotés de lois de composition."
        level="CPGE MPSI / PCSI / MP"
        duration="4.0h"
        objectives={[
          "Comprendre l'organisation axiomatique abstraite des ensembles de nombres.",
          "Modéliser et vérifier la stabilité de sous-structures (sous-groupes, idéaux).",
          "Exploiter les morphismes pour lier des structures apparemment distinctes.",
          "Décomposer et structurer les ensembles cycliques finis comme la congruence arithmétique."
        ]}
      />

      <InfoBlock id="cpge1-intro-block" type="info" title="L'esprit des structures en CPGE">
        En classes préparatoires, l'algèbre générale s'affranchit du calcul numérique brut pour s'intéresser à la forme logique des opérations. En étudiant les **groupes**, les **anneaux** et les **corps**, vous n'étudiez plus des objets isolés, mais les règles universelles qui gouvernent les symétries géométriques, la cryptographie asymétrique (RSA), ou les équations de polynômes complexes (Théorie de Galois).
      </InfoBlock>

      <Section id="cpge1-sec-1" title="1. Groupes et Sous-groupes" color="slate" icon="🛡️">
        <div className="space-y-4">
          <p>
            Soit {"$G$"} un ensemble muni d'une loi de composition interne (LCI) notée {"$\\ast$"}. Le couple {"$(G, \\ast)$"} est appelé un **groupe** s'il vérifie les quatre axiomes fondamentaux suivants :
          </p>

          <BentoGrid id="cpge1-bento-axioms">
            <BentoCard id="cpge1-bc-assoc" title="1. Associativité" color="slate">
              <p className="text-xs text-zinc-500 mb-2">La loi est indépendante des groupements parenthésés :</p>
              <div className="font-mono text-center p-2.5 bg-white dark:bg-slate-950 rounded border text-indigo-700 dark:text-indigo-400 font-bold">
                {"$$\\forall (a,b,c) \\in G^3, \\quad (a \\ast b) \\ast c = a \\ast (b \\ast c)$$"}
              </div>
            </BentoCard>

            <BentoCard id="cpge1-bc-neutre" title="2. Élément Neutre" color="indigo">
              <p className="text-xs text-indigo-500/80 mb-2">Il existe un pivot stable neutre unique, souvent codé e :</p>
              <div className="font-mono text-center p-2.5 bg-white dark:bg-slate-950 rounded border text-indigo-700 dark:text-indigo-400 font-bold">
                {"$$\\exists e \\in G, \\quad \\forall a \\in G, \\quad a \\ast e = e \\ast a = a$$"}
              </div>
            </BentoCard>

            <BentoCard id="cpge1-bc-sym" title="3. Symétrisation" color="purple" colSpan={3}>
              <p className="text-xs text-zinc-400 mb-2">Chaque élément contient un opposé ou un inverse par rapport à l'unité neutre :</p>
              <div className="font-mono text-center p-3 bg-white dark:bg-slate-950 rounded border text-purple-700 dark:text-purple-400 font-bold">
                {"$$\\forall a \\in G, \\quad \\exists a' \\in G, \\quad a \\ast a' = a' \\ast a = e$$"}
              </div>
            </BentoCard>
          </BentoGrid>

          <InfoBlock id="cpge1-subgroup-info" type="definition" title="Caractérisation des sous-groupes">
            Une partie non vide {"$H \\subset G$"} est un **sous-groupe** de {"$(G, \\ast)$"} si et seulement si elle est stable par composition et par inversion. On résume cela par le critère d'évaluation CPGE :
            <div className="font-mono text-center my-3 p-3 bg-white dark:bg-slate-900 border rounded text-emerald-700 dark:text-emerald-400 font-black">
              {"$$H \\neq \\emptyset \\quad \\text{et} \\quad \\forall (x, y) \\in H^2, \\quad x \\ast y^{-1} \\in H$$"}
            </div>
            Où {"$y^{-1}$"} représente le symétrique de {"$y$"} pour la loi de groupe globale.
          </InfoBlock>

          <TipBanner id="cpge1-lagrange-banner" type="info" title="Théorème de Lagrange (Groupes Finis)">
            Si {"$G$"} est un groupe fini et {"$H$"} un sous-groupe de {"$G$"}, alors le cardinal de {"$H$"} divise nécessairement le cardinal de {"$G$"}. Autrement dit :
            <div className="font-mono text-center my-2 p-1.5 text-indigo-700 dark:text-indigo-400 font-extrabold text-sm" id="lagrange-eq">
              {"$$\\text{Card}(H) \\text{ divise } \\text{Card}(G)$$"}${"\\quad \\implies \\quad"} les tailles possibles des sous-groupes sont limitées aux diviseurs entiers globaux.
            </div>
          </TipBanner>
        </div>
      </Section>

      <Section id="cpge1-sec-2" title="2. Morphismes de Groupes" color="indigo" icon="⚡">
        <div className="space-y-4">
          <p>
            Un **morphisme** (ou homomorphisme) d'un groupe {"$(G, \\ast)$"} vers un groupe {"$(H, \\cdot)$"} est une application {"$f: G \\to H$"} qui respecte les structures d'exploitation sous-jacentes :
          </p>
          <div className="font-mono text-center p-4 bg-slate-50 dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 text-indigo-700 dark:text-indigo-450 font-black text-lg" id="morph-eq">
            {"$$\\forall (x, y) \\in G^2, \\quad f(x \\ast y) = f(x) \\cdot f(y)$$"}
          </div>

          <p>
            Ce simple axiome engendre deux ensembles fondamentaux permettant d'identifier complètement l'application linéaire ou algébrique :
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-4" id="kernel-image-grid">
            <div className="p-5 border border-slate-200 dark:border-slate-800 rounded-2xl bg-card" id="kernel-box">
              <span className="text-xs uppercase font-bold text-slate-400">Le Noyau (Kernel) :</span>
              <div className="font-mono text-xs font-black p-2 bg-slate-100 dark:bg-slate-950 border rounded my-2 text-indigo-700 dark:text-indigo-400">
                {"$$\\operatorname{Ker}(f) = \\{ x \\in G \\mid f(x) = e_H \\}$$"}
              </div>
              <p className="text-xs text-slate-500 leading-normal">
                C'est un sous-groupe distingué de {"$G$"}. Règle d'or : {"$f$"} est injectif si et seulement si son noyau est réduit au neutre singleton {"$\\operatorname{Ker}(f) = \\{ e_G \\}$"}.
              </p>
            </div>

            <div className="p-5 border border-slate-200 dark:border-slate-800 rounded-2xl bg-card" id="image-box">
              <span className="text-xs uppercase font-bold text-slate-400">L'Image (Im) :</span>
              <div className="font-mono text-xs font-black p-2 bg-slate-100 dark:bg-slate-950 border rounded my-2 text-indigo-700 dark:text-indigo-400">
                {"$$\\operatorname{Im}(f) = \\{ f(x) \\mid x \\in G \\}$$"}
              </div>
              <p className="text-xs text-slate-500 leading-normal">
                C'est un sous-groupe de {"$H$"}. L'application est surjective si et seulement si {"$\\operatorname{Im}(f) = H$"}.
              </p>
            </div>
          </div>
        </div>
      </Section>

      <Section id="cpge1-sec-3" title="3. Anneaux et Corps" color="purple" icon="💍">
        <div className="space-y-4">
          <p>
            Une structure possède un **degré de richesse** supérieur si elle est dotée de deux lois qui interagissent de façon harmonieuse.
          </p>

          <div className="bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 rounded-[2rem] space-y-4" id="ring-def-card">
            <h4 className="font-bold text-lg text-indigo-900 dark:text-indigo-400">Structure d'Anneau {"$(A, +, \\times)$"} :</h4>
            <p className="text-xs text-slate-500 leading-relaxed">
              1. {"$(A, +)$"} est un groupe abélien (commutatif). Son élément neutre est noté {"$0_A$"}.
              <br />
              2. La loi {"$\\times$"} est interne, associative et possède un élément neutre (unitaire), noté {"$1_A$"}.
              <br />
              3. La loi {"$\\times$"} est **distributive** par rapport à la loi {"$+$"} :
            </p>
            <div className="font-mono text-center py-2 bg-white dark:bg-slate-950 rounded border text-indigo-700 dark:text-indigo-400 font-bold text-xs" id="distrib-eq">
              {"$$\\forall (a,b,c) \\in A^3, \\quad a \\times (b + c) = a \\times b + a \\times c \\quad \\text{et} \\quad (b + c) \\times a = b \\times a + c \\times a$$"}
            </div>
          </div>

          <InfoBlock id="cpge1-field-info" type="reminder" title="Axiome de Corps (Field)">
            Un **corps** {"$(K, +, \\times)$"} est un anneau commutatif unitaire non nul où tout élément non nul est inversible pour la loi multiplicative {"$\\times$"}. Les exemples absolus en MP sont les ensembles infinis classiques :
            <div className="font-mono text-center my-3 p-2 bg-slate-100 dark:bg-slate-950 border rounded font-black text-rose-700 dark:text-rose-400" id="fields-list">
              {"$$\\mathbb{Q} \\quad , \\quad \\mathbb{R} \\quad , \\quad \\mathbb{C}$$"}
            </div>
            Tout corps commutatif est nécessairement intègre (c'est-à-dire qu'un produit de facteurs y est nul si et seulement si l'un des termes est nul).
          </InfoBlock>
        </div>
      </Section>

      <Section id="cpge1-sec-4" title="4. Visualisation de l'Arithmétique Modulaire" color="slate" icon="🧮">
        <ModularStructureSim />
      </Section>

      <Section id="cpge1-exercises" title="Exercices Corrigés de Niveau Spé" color="amber" icon="🧠">
        <InteractiveExercise 
          id="cpge1-ex-1"
          title="Exercice 1 : Établir si une loi exotique définit une structure de groupe"
          question={
            <>
              Soit l'ensemble ouvert de réels {"$G = ]-1 ; 1[$"}. On définit sur cet ensemble une loi de composition interne exotique notée {"$\\ast$"} par :
              <br />
              {"$$\\forall (x, y) \\in G^2, \\quad x \\ast y = \\frac{x + y}{1 + xy}$$"}.
              <br />
              Démontrer que le couple {"$(G, \\ast)$"} forme un groupe abélien commutatif.
            </>
          }
          steps={[
            <>
              <strong>Étape 1 : Vérification de la LCI et de la commutativité</strong>
              <p className="mt-2 text-sm leading-relaxed">
                • Commutativité évidente : puisque l'addition et la multiplication sont commutatives dans {"$\\mathbb{R}$"} :
                <br />
                {"$$x \\ast y = \\frac{x + y}{1 + xy} = \\frac{y + x}{1 + yx} = y \\ast x$$"}.
                <br />
                • Montrons que la loi est stable dans le filtre ouvert de taille {"$]-1; 1[$"}. Si {"$x, y \\in ]-1; 1[$"}, prouvons que {"$-1 < \\frac{x+y}{1+xy} < 1$"}.
                <br />
                Calculons : {"$$1 - (x \\ast y)^2 = 1 - \\frac{(x+y)^2}{(1+xy)^2} = \\frac{(1+xy)^2 - (x+y)^2}{(1+xy)^2} = \\frac{(1 - x^2)(1 - y^2)}{(1+xy)^2}$$"}.
                <br />
                Puisque {"$x^2 < 1$"} et {"$y^2 < 1$"}, le numérateur et le dénominateur sont strictement positifs. Donc {"$(x \\ast y)^2 < 1$"}, d'où {"$x \\ast y \\in ]-1;1[$"}. La loi est donc interne.
              </p>
            </>,
            <>
              <strong>Étape 2 : Recherche de l'élément neutre unique e</strong>
              <p className="mt-2 text-sm leading-relaxed">
                Cherchons {"$e \\in ]-1 ; 1[$"} tel que pour tout {"$x \\in ]-1 ; 1[$"}, {"$x \\ast e = x$"}.
                L'équation s'écrit :
                {"$$\\frac{x + e}{1 + xe} = x \\implies x + e = x(1 + xe) = x + e x^2 \\implies e(1 - x^2) = 0$$"}.
                <br />
                Puisque {"$x \\in ]-1 ; 1[$"}, on a {"$1 - x^2 \\neq 0$"}, ce qui force trivialement :
                <span className="font-mono block text-center font-bold text-indigo-700 mt-1">{"$e = 0$"}.</span>
                0 appartient bien à l'ouvert, c'est le neutre unique.
              </p>
            </>,
            <>
              <strong>Étape 3 : Découverte du symétrique et conclusion</strong>
              <p className="text-sm mt-1 leading-relaxed">
                Pour tout {"$x \\in G$"}, on cherche un symétrique {"$x'$"} tel que {"$x \\ast x' = 0$"}.
                L'équation donne :
                {"$$\\frac{x + x'}{1 + xx'} = 0 \\implies x + x' = 0 \\implies x' = -x$$"}.
                <br />
                Si {"$x \\in ]-1 ; 1[$"}, alors {"$x' = -x$"} appartient de même à l'intervalle. L'associativité se montre simplement en développant sans encombre {"$(x \\ast y) \\ast z$"}.
              </p>
              <div className="font-mono text-center my-3 p-2.5 bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-400 border rounded font-black text-sm" id="cpge1-ex1-result">
                Conclusion : (]-1 ; 1[, *) est bien un groupe abélien commutatif. Il est d'ailleurs isomorphe à (ℝ, +) via la fonction tanh(x) !
              </div>
            </>
          ]}
        />

        <InteractiveExercise 
          id="cpge1-ex-2"
          title="Exercice 2 : Structure d'un idéal de l'anneau des entiers Z"
          question={
            <>
              Soit l'anneau commutatif unitaire {"$(\\mathbb{Z}, +, \\times)$"}.
              <br />
              On définit l'ensemble {"$I = 4\\mathbb{Z} \\cap 6\\mathbb{Z}$"}.
              <br />
              1. Identifier précisément le sous-ensemble {"$I$"} sous la forme d'un produit d'entiers {"$k\\mathbb{Z}$"}.
              <br />
              2. Démontrer que {"$I$"} est un idéal de l'anneau des entiers.
            </>
          }
          steps={[
            <>
              <strong>Étape 1 : Interpréter l'intersection d'ensembles multiples</strong>
              <p className="mt-2 text-sm leading-relaxed">
                L'ensemble {"$4\\mathbb{Z}$"} désigne l'ensemble des multiples de 4. De même, {"$6\\mathbb{Z}$"} désigne les multiples de 6.
                L'intersection de ces deux ensembles, {"$I$"}, contient tous les entiers qui sont simultanément multiples de 4 et de 6.
                L'entier minimal positif commun est donc le Plus Petit Commun Multiple (PPCM) :
                {"$$\\operatorname{PPCM}(4, 6) = 12$$"}.
                On en déduit donc l'égalité d'ensembles :
                <span className="font-mono block text-center font-black text-indigo-700 mt-1">{"$I = 12\\mathbb{Z}$"}</span>
              </p>
            </>,
            <>
              <strong>Étape 2 : Rappel exhaustif de la définition d'un idéal</strong>
              <p className="mt-2 text-sm leading-relaxed">
                Une partie {"$J$"} d'un anneau {"$A$"} est appelée un **idéal** de {"$A$"} si :
                <br />
                1. {"$(J, +)$"} est un sous-groupe du groupe additif {"$(A, +)$"}.
                <br />
                2. L'idéal « absorbe » les multiplications par des éléments extérieurs :
                {"$$\\forall (x, a) \\in J \\times A, \\quad a \\times x \\in J \\quad \\text{et} \\quad x \\times a \\in J$$"}.
              </p>
            </>,
            <>
              <strong>Étape 3 : Application et preuve de conformité d'idéal principal</strong>
              <p className="text-sm mt-1 leading-relaxed">
                • Pour notre sous-ensemble {"$I = 12\\mathbb{Z}$"} :
                C'est le sous-groupe additif bien connu engendré par l'entier 12.
                <br />
                • Test d'absorption : soient {"$x \\in 12\\mathbb{Z}$"} (donc {"$x = 12k$"} avec {"$k \\in \\mathbb{Z}$"}) et un entier extérieur quelconque {"$k' \\in \\mathbb{Z}$"}.
                <br />
                On a : {"$k' \\times x = k' \\times (12k) = 12 \\times (k'k)$"}.
                Puisque {"$k'k \\in \\mathbb{Z}$"}, l'élément produit est bel et bien un multiple de 12.
              </p>
              <div className="font-mono text-center my-2 p-2 bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-400 border rounded font-black text-sm" id="cpge1-ex2-result">
                I = 12ℤ est donc un idéal principal de l'anneau principal ℤ.
              </div>
            </>
          ]}
        />
      </Section>

      <Section id="cpge1-faq" title="Questions Courantes (FAQ)" color="slate" icon={<HelpCircle className="text-indigo-600 w-5 h-5"/>}>
        <AccordionFAQ id="cpge1-faq-accordion" items={[
          {
            question: "Quelle est la différence subtile entre un homomorphisme et un isomorphisme ?",
            answer: "Un morphisme d'homomorphisme conserve les caractéristiques opératoires. Un isomorphisme est simplement un homomorphisme qui s'avère bijectif. S'il existe un isomorphisme f entre deux groupes G et H, alors ces groupes sont totalement identiques d'un point de vue de l'algèbre pure (mêmes orbites, mêmes ordres, mêmes sous-groupes), seule la notation de leurs éléments diffère."
          },
          {
            question: "Qu'est-ce qu'un groupe distingué (ou normal) en algèbre avancée ?",
            answer: "Un sous-groupe H d'un groupe G est dit distingué (ou normal) si ses classes à gauche et à droite coïncident pour chaque élément, soit : ∀g ∈ G, gH = Hg. C'est la condition sine qua non permettant de former de manière mathématiquement cohérente un nouveau groupe appelé groupe quotient, noté G/H."
          },
          {
            question: "Comment identifier si un anneau est intègre de façon rapide ?",
            answer: "Un anneau est intègre s'il est commutatif non nul, et qu'il ne contient pas de diviseurs de zéro. C'est-à-dire que l'égalité a * b = 0 implique toujours a = 0 ou b = 0. Par exemple, l'anneau Z/6Z n'est pas intègre car 2 * 3 = 0 modulo 6 alors que 2 et 3 sont non nuls !"
          }
        ]} />
      </Section>

      <Section id="cpge1-flashcards" title="Cartes Mémo (Flashcards)" color="purple" icon="🃏">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Flashcard 
            id="cpge1-fc-1"
            front={<>Quelle est la formule liant l'ordre d'un élément x de son exposant neutre ?</>}
            back={<>L'ordre o(x) est le plus petit entier k &gt; 0 vérifiant <strong>{"$x^k = e$"}.</strong> En écriture additive, cela correspond de même à k &times; x = 0.</>}
          />
          <Flashcard 
            id="cpge1-fc-2"
            front={<>Qu'est-ce qu'un idéal d'un anneau d'un point de vue structural ?</>}
            back={<>C'est un sous-groupe additif stable qui absorbe tous les produits avec les éléments de l'anneau extérieur. Tout idéal de ℤ s'écrit sous la forme kℤ, l'anneau est dit principal.</>}
          />
        </div>
      </Section>

      <Section id="cpge1-quiz" title="Quiz de Validation" color="indigo" icon="🎯">
        <Quiz 
          id="cpge1-quiz-comp"
          questions={[
            {
              question: "Si G est un groupe cyclique d'ordre 12, que peut-être l'ordre d'un sous-groupe H d'après le théorème de Lagrange ?",
              options: ["5", "8", "4"],
              correctAnswer: 2,
              explanation: "Rappel : Lagrange impose que Card(H) divise Card(G). La taille possible doit diviser 12. Les seuls choix admissibles sont 1, 2, 3, 4, 6 et 12. 4 est le seul choix valide."
            },
            {
              question: "Laquelle de ces structures algébriques simples ne forme pas un groupe pour la seconde loi multiplicative associée ?",
              options: ["(ℝ*, ×)", "(ℤ, ×)", "(ℚ*, ×)"],
              correctAnswer: 1,
              explanation: "Dans (ℤ, ×), seuls 1 et -1 possèdent un inverse. Les éléments comme 5 ou 2 n'ont pas d'inverse multiplicatif dans l'ensemble des entiers."
            },
            {
              question: "À quelle condition impérative l'anneau modulaire ℤ/nℤ est-il élevé au rang de Corps commutatif ?",
              options: ["n est un entier pair", "n est un nombre premier", "n est divisible par 10"],
              correctAnswer: 1,
              explanation: "Si et seulement si n est un nombre premier. Dans ce cas, tous les résidus non nuls sont premiers avec n, donc inversibles d'après le théorème de Bézout."
            }
          ]}
        />
      </Section>

      <div onClick={() => validateCourse(courseId)} id="checklist-trigger">
        <InteractiveChecklist id="cpge1-checklist" items={checklistItems} />
      </div>
    </div>
  );
};

export default Course_CPGE_01_Structures_Algebriques;
