import React, { useState } from 'react';
import { 
  CourseHeader, Section, InfoBlock, Quiz, InteractiveChecklist, 
  FormulaBox, InteractiveExercise, AccordionFAQ, Flashcard, TipBanner
} from '../../components/SharedUI';
import { MathComponent } from "../../components/MathComponent";
import { HelpCircle, RefreshCw, Zap } from 'lucide-react';

const Course_Licence_Maths_Groupes: React.FC<{
  onValidateCourse: () => void;
  isCompleted: boolean;
}> = ({ onValidateCourse, isCompleted }) => {
  // Cayley Table State
  const [n, setN] = useState<number>(5);
  const [op, setOp] = useState<'add' | 'mul'>('add');
  const [selectedElement, setSelectedElement] = useState<number>(1);

  // Compute elements in our set
  // For 'add', it's Z/nZ -> {0, 1, ..., n-1}
  // For 'mul', we can show Z/nZ but warn about structure, or better, show the Group of Units (Z/nZ)* which contains only elements coprime to n!
  const getElements = () => {
    if (op === 'add') {
      return Array.from({ length: n }, (_, i) => i);
    } else {
      // elements coprime to n
      const gcd = (a: number, b: number): number => b === 0 ? a : gcd(b, a % b);
      return Array.from({ length: n }, (_, i) => i).filter(x => gcd(x, n) === 1);
    }
  };

  const elements = getElements();
  const identity = op === 'add' ? 0 : 1;

  // Compute inverse of a given element
  const getInverse = (x: number): number | null => {
    if (op === 'add') {
      return (n - x) % n;
    } else {
      // Find y such that (x * y) % n === 1
      for (const y of elements) {
        if ((x * y) % n === 1) return y;
      }
    }
    return null;
  };

  // Compute subgroup generated by selectedElement
  const getSubgroupGeneratedBy = (g: number) => {
    const orbit: number[] = [];
    let current = g;
    let limit = 0;
    if (op === 'add') {
      while (!orbit.includes(current) && limit < 50) {
        orbit.push(current);
        current = (current + g) % n;
        limit++;
      }
    } else {
      while (!orbit.includes(current) && limit < 50) {
        orbit.push(current);
        current = (current * g) % n;
        limit++;
      }
    }
    // ensure order of elements is sorted for neatness
    return [...orbit].sort((a, b) => a - b);
  };

  const generatedSubgroup = getSubgroupGeneratedBy(selectedElement);

  return (
    <div className="max-w-5xl mx-auto pb-16 px-4 md:px-0">
      <CourseHeader 
        acronym="MATH-LIC-GRP"
        title="Licence Algèbre : Théorie des Groupes"
        subtitle="Structures algébriques abstraites, sous-groupes, morphismes, théorème de Lagrange et quotients."
        duration="1h 40"
        level="Licence Mathématiques (L2/L3)"
        prerequisites={["Ensembles et relations", "Arithmétique modulaire (Bezout, Gauss)", "Algèbre linéaire fondamentale"]}
        objectives={[
          "Maîtriser les axiomes des groupes et la détection d'isomorphismes.",
          "Interpréter les structures de groupes cycliques et d'arbres de sous-groupes.",
          "Appliquer le Théorème de Lagrange aux contraintes d'ordres des sous-structures.",
          "Comprendre le rôle pivot du noyau d'un morphisme et des invariants quotient."
        ]}
      />

      <Section title="🧱 Définition Fondamentale de Groupe" icon="🧱" color="indigo">
        <p className="text-base leading-relaxed text-slate-700 dark:text-slate-300">
          En licence de mathématiques fondamentales, l'algèbre générale étudie les structures en elles-mêmes, dépouillées d'éléments numériques particuliers. Le concept de <strong>groupe</strong> est la brique la plus répandue. Un groupe capte l'essence mathématique des <strong>symétries</strong> de la nature, de la physique des cristaux aux équations polynomiales (Théorie de Galois).
        </p>

        <InfoBlock type="definition" title="Structure de Groupe (G, ★)">
          Un groupe est un ensemble non-vide <MathComponent math="G" /> muni d'une loi de composition interne <MathComponent math="\star" /> vérifiant :
          <ul className="list-grid pl-6 mt-3 space-y-2 text-slate-800 dark:text-slate-200 text-sm font-semibold">
            <li>
              <span>1. Associativité : </span> 
              <span className="font-mono text-indigo-600 block sm:inline">{"$\\forall a,b,c \\in G, \\ (a \\star b) \\star c = a \\star (b \\star c)$"}</span>
            </li>
            <li>
              <span>2. Existence d'un élément neutre : </span>
              <span className="font-mono text-indigo-600 block sm:inline">{"$\\exists e \\in G, \\ \\forall a \\in G, \\ a \\star e = e \\star a = a$"}</span>
            </li>
            <li>
              <span>3. Existence d'un symétrique : </span>
              <span className="font-mono text-indigo-600 block sm:inline">{"$\\forall a \\in G, \\ \\exists a' \\in G, \\ a \\star a' = a' \star a = e$"}</span>
            </li>
          </ul>
          <p className="mt-3 text-sm font-semibold">
            Si la loi est également multiplicativement commutative (<MathComponent math="a \star b = b \star a" />), le groupe est dit <strong>abélien</strong> ou commutatif.
          </p>
        </InfoBlock>

        <TipBanner type="warning" title="Piège classique : Loi de composition externe">
          La loi de composition doit être <strong>interne</strong>. C'est-à-dire que pour toute paire <MathComponent math="(a, b) \in G^2" />, le résultat <MathComponent math="a \star b" /> doit absolument être un élément de <MathComponent math="G" />. Si le résultat sort de l'ensemble, la structure n'est pas un groupe (ex: soustraction sur <MathComponent math="\mathbb{N}" />).
        </TipBanner>
      </Section>

      <Section title="⚙️ Simulateur Interactif des Tables de Cayley" icon="📊" color="purple">
        <p className="mb-6 text-sm md:text-base text-slate-700 dark:text-slate-300">
          Visualisez concrètement les axiomes d'un groupe en explorant sa <strong>Table de Cayley</strong> (la table de multiplication du groupe). Choisissez l'ordre <MathComponent math="n" /> et la loi pour former soit le groupe additif cyclic <MathComponent math="(\mathbb{Z}/n\mathbb{Z}, +)" />, soit le groupe multiplicatif de ses unités inversibles <MathComponent math="(\mathbb{Z}/n\mathbb{Z})^\times" /> !
        </p>

        <div className="bg-slate-50 dark:bg-slate-900 border rounded-3xl p-6 md:p-8 space-y-8 shadow-inner">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-center">
            <div>
              <label className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-2">Modifier l'Ordre n</label>
              <select 
                value={n} 
                onChange={(e) => {
                  const val = parseInt(e.target.value);
                  setN(val);
                  setSelectedElement(1);
                }}
                className="w-full bg-card border border-border-strong/70 text-foreground px-4 py-3 rounded-xl focus:ring-2 focus:ring-indigo-500 font-bold outline-none"
              >
                {[3, 4, 5, 6, 7, 8, 9].map((val) => (
                  <option key={val} value={val}>n = {val}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-2">Loi algébrique (★)</label>
              <div className="flex bg-card border rounded-xl p-1 gap-1">
                <button
                  onClick={() => { setOp('add'); setSelectedElement(1); }}
                  className={`flex-1 py-2 rounded-lg font-bold text-xs transition-all ${op === 'add' ? 'bg-indigo-600 text-white shadow' : 'text-slate-500'}`}
                >
                  Addition (+)
                </button>
                <button
                  onClick={() => { setOp('mul'); setSelectedElement(1); }}
                  className={`flex-1 py-2 rounded-lg font-bold text-xs transition-all ${op === 'mul' ? 'bg-indigo-600 text-white shadow' : 'text-slate-500'}`}
                >
                  Multiplication (×)
                </button>
              </div>
            </div>

            <div>
              <label className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-2">Générer Sous-Groupe</label>
              <select 
                value={selectedElement} 
                onChange={(e) => setSelectedElement(parseInt(e.target.value))}
                className="w-full bg-card border border-border-strong/70 text-foreground px-4 py-3 rounded-xl focus:ring-2 focus:ring-indigo-500 font-bold outline-none"
              >
                {elements.map((el) => (
                  <option key={el} value={el}>Générateur g = {el}</option>
                ))}
              </select>
            </div>
          </div>

          {/* Cayley Table */}
          <div className="bg-card border border-border-strong/50 rounded-2xl p-6 overflow-x-auto">
            <h4 className="font-bold text-indigo-950 dark:text-indigo-200 mb-4 flex items-center justify-between">
              <span>Table de Cayley de la structure modulaire</span>
              <span className="text-xs font-mono py-1 px-2.5 bg-indigo-50 dark:bg-indigo-950 border border-indigo-150 text-indigo-700 rounded-md">
                {op === 'add' ? `(Z/${n}Z, +)` : `(Z/${n}Z)* multiplicatif`}
              </span>
            </h4>
            
            <table className="min-w-full font-mono text-center border-collapse">
              <thead>
                <tr>
                  <th className="p-3 border-r border-b-2 bg-slate-100 dark:bg-slate-800 text-indigo-600 font-extrabold text-sm">★</th>
                  {elements.map((col) => (
                    <th key={col} className="p-3 border-b-2 bg-slate-50 dark:bg-slate-800 text-foreground font-bold text-xs">
                      {col}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {elements.map((row) => (
                  <tr key={row} className="hover:bg-indigo-50/25 dark:hover:bg-indigo-900/10">
                    <td className="p-3 border-r bg-slate-50 dark:bg-slate-800 font-bold text-xs text-foreground">{row}</td>
                    {elements.map((col) => {
                      const ans = op === 'add' ? (row + col) % n : (row * col) % n;
                      const isIdentity = ans === identity;
                      const isGOrbed = generatedSubgroup.includes(ans);
                      
                      let cellColor = "bg-card text-foreground";
                      if (isIdentity) cellColor = "bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 font-extrabold border border-emerald-200/50";
                      else if (isGOrbed) cellColor = "bg-purple-50 dark:bg-purple-950/40 text-purple-700 font-semibold";

                      return (
                        <td 
                          key={col} 
                          className={`p-3 border border-border-strong/40 text-xs transition-colors duration-200 ${cellColor}`}
                          title={`row ${row} ★ col ${col} = ${ans}`}
                        >
                          {ans}
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
            
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center text-xs text-slate-400 mt-4 gap-2 leading-relaxed">
              <span>🟢 Les cases vertes identifient l'<strong>élément neutre e = {identity}</strong>.</span>
              <span>🟣 Les cases mauves indiquent l'orbite d'actions générées par <strong>g = {selectedElement}</strong>.</span>
            </div>
          </div>

          {/* Subgroup generated explanation card */}
          <div className="p-6 bg-card border rounded-2xl">
            <h5 className="font-bold text-slate-500 uppercase tracking-wider text-xs mb-3 flex items-center gap-1.5">
              <Zap size={16} className="text-purple-500 animate-pulse" /> Sous-groupe engendré ⟨{selectedElement}⟩
            </h5>
            <div className="flex flex-col sm:flex-row sm:items-center gap-4">
              <div className="p-4 bg-purple-50 dark:bg-purple-950/30 border border-purple-150 rounded-xl font-mono text-lg font-bold text-purple-800 dark:text-purple-300">
                H = {"{"} {generatedSubgroup.join(', ')} {"}"}
              </div>
              <div className="flex-1 text-sm text-slate-600 dark:text-slate-300 space-y-1.5 font-medium">
                <p>• Ordre du sous-groupe |H| = <strong className="text-indigo-600">{generatedSubgroup.length}</strong>.</p>
                <p>• Ordre du groupe global |G| = <strong className="text-indigo-600">{elements.length}</strong>.</p>
                <p>
                  • Vérification de Lagrange : le rapport {" |G| / |H| = "} 
                  <strong className="text-emerald-600">{(elements.length / generatedSubgroup.length).toFixed(0)}</strong> qui est un entier strict ! L'ordre de H divise bien l'ordre total de G.
                </p>
              </div>
            </div>
          </div>
        </div>
      </Section>

      <Section title="⚖️ Théorème de Lagrange et Cardinalité" icon="📐" color="emerald">
        <p className="mb-4 text-base leading-relaxed text-slate-700 dark:text-slate-300">
          Pour les groupes de cardinal fini, l'arborescence des sous-groupes n'est pas le fruit du hasard. L'arithmétique dicte une contrainte rigide quant à l'ordre des sous-groupes admissibles.
        </p>

        <FormulaBox 
          title="Théorème de Lagrange" 
          math="|H| \ \text{divise} \ |G|" 
        />

        <p className="my-4 text-base text-slate-700 dark:text-slate-300 leading-relaxed">
          Si <MathComponent math="G" /> est un groupe de cardinal fini (son ordre <MathComponent math="|G|" /> est un entier positif) et <MathComponent math="H" /> un sous-groupe de <MathComponent math="G" />, alors l'ordre de <MathComponent math="H" /> divise nécessairement l'ordre de <MathComponent math="G" />.
        </p>

        <InfoBlock type="reminder" title="Classes d'équivalence et indice">
          On définit la relation d'équivalence modulo <MathComponent math="H" /> par :
          <MathComponent block math="x \sim_g y \iff x^{-1}y \in H" />
          Les classes d'équivalence forment une partition de <MathComponent math="G" />. Chaque classe (à gauche) s'écrit sous la forme <MathComponent math="xH = \{xh, h \in H\}" />. Elles ont toutes exactement le même cardinal <MathComponent math="|H|" />.
          Le nombre de classes distinctes est appelé l'<strong>index de H dans G</strong>, noté <MathComponent math="[G:H]" />. Par partitionnement direct, on en déduit :
          <MathComponent block math="[G:H] = \frac{|G|}{|H|}" />
        </InfoBlock>
      </Section>

      <Section title="🔄 Morphismes et Équivalences Quotient" icon="🌀" color="amber">
        <p className="mb-4 text-base text-slate-700 dark:text-slate-300 leading-relaxed">
          Pour comparer ou simplifier des structures de groupes différents, on étudie les applications qui respectent les lois de composition. Ce sont les <strong>morphismes de groupes</strong>.
        </p>

        <InfoBlock type="definition" title="Morphisme de groupes">
          Une application <MathComponent math="f" /> d'un groupe <MathComponent math="(G, \cdot)" /> dans un second groupe <MathComponent math="(G', \star)" /> est qualifiée de morphisme de groupes si :
          <MathComponent block math="\forall x, y \in G, \ f(x \cdot y) = f(x) \star f(y)" />
          Si <MathComponent math="f" /> est bijective, <MathComponent math="f" /> est un <strong>isomorphisme</strong> (on écrit {"$G \\cong G'$"}). Sur le plan des structures, les deux groupes se comportent de manière rigoureusement identique.
        </InfoBlock>

        <h3 className="text-xl font-bold mt-8 mb-3 text-amber-950 dark:text-amber-300">Noyau et Image d’un morphisme</h3>
        <p className="mb-4 text-base text-slate-700 dark:text-slate-300 leading-relaxed">
          Pour caractériser un morphisme <MathComponent math="f: G \to G'" />, on étudie deux sous-groupes clés :
        </p>
        <ul className="list-disc pl-8 mb-6 space-y-2 text-sm font-semibold text-slate-700 dark:text-slate-300">
          <li>
            <strong>Le Noyau (Ker f) :</strong> L'ensemble des antécédents du neutre de G' : <MathComponent math="\text{Ker}(f) = \{x \in G \mid f(x) = e_{G'}\}" />. C'est un sous-groupe <strong>distingué</strong> de G. Un morphisme est injectif si et seulement si son noyau est trivial : <MathComponent math="\text{Ker}(f) = \{e_G\}" />.
          </li>
          <li>
            <strong>L'Image (Im f) :</strong> L'ensemble des images de G par f : <MathComponent math="\text{Im}(f) = \{f(x) \mid x \in G\}" />. C'est un sous-groupe de G'. f est surjetif si et seulement si <MathComponent math="\text{Im}(f) = G'" />.
          </li>
        </ul>

        <FormulaBox 
          title="Premier Théorème d'Isomorphisme" 
          math="G/\text{Ker}(f) \ \cong \ \text{Im}(f)" 
        />
      </Section>

      <Section title="⚔️ Exercices Résolus d'Algèbre Générale" icon="🛠️" color="purple">
        <InteractiveExercise
          title="Exercice 1 : Unicité de l'élément neutre"
          question={<p>Démontrer par contradiction ou logique algébrique directe qu'un groupe <MathComponent math="(G, \star)" /> admet un unique élément neutre.</p>}
          steps={[
            <div className="bg-muted p-4 rounded-xl border border-border">
              <p className="font-bold text-indigo-900 dark:text-indigo-100">Étape 1 : Hypothèse d'existence duale</p>
              <p className="mt-2 text-sm leading-relaxed">
                Supposons par l'absurde que le groupe <MathComponent math="(G, \star)" /> contienne deux éléments neutres distincts, disons <MathComponent math="e_1" /> et <MathComponent math="e_2" />.
              </p>
            </div>,
            <div className="bg-muted p-4 rounded-xl border border-border">
              <p className="font-bold text-indigo-900 dark:text-indigo-100">Étape 2 : Appliquer les axiomes sur le produit e_1 🟊 e_2</p>
              <p className="mt-2 text-sm leading-relaxed">
                Considérons maintenant l'élément composé <MathComponent math="e_1 \star e_2" />.
                <br />
                • D'une part, comme <MathComponent math="e_1" /> est un élément neutre pour tout élément du groupe, le produit de <MathComponent math="e_1" /> avec n'importe quel élément renvoie cet élément :
                <MathComponent block math="e_1 \star e_2 = e_2" />
              </p>
            </div>,
            <div className="bg-emerald-50/50 dark:bg-emerald-900/20 p-4 rounded-xl border border-emerald-100 dark:border-emerald-800/60 font-bold text-emerald-900 dark:text-emerald-100">
              <p>Étape 3 : Égalisation et conclusion</p>
              <p className="mt-2 text-sm leading-relaxed">
                • D'autre part, comme <MathComponent math="e_2" /> est également un élément neutre de G :
                <MathComponent block math="e_1 \star e_2 = e_1" />
                <br />
                En confrontant les deux égalités, on conclut de manière directe :
                <MathComponent block math="e_1 = e_1 \star e_2 = e_2 \implies e_1 = e_2" />
                L'élément neutre d'un groupe est donc nécessairement unique.
              </p>
            </div>
          ]}
        />

        <InteractiveExercise
          title="Exercice 2 : Groupes d'ordre premier"
          question={<p>Soit <MathComponent math="G" /> un groupe fini d'ordre <MathComponent math="p" />, où <MathComponent math="p" /> désigne un nombre premier. Montrer que <MathComponent math="G" /> est nécessairement cyclique.</p>}
          steps={[
            <div className="bg-muted p-4 rounded-xl border border-border">
              <p className="font-bold text-indigo-900 dark:text-indigo-100">Étape 1 : Choisir un élément non-neutre</p>
              <p className="mt-2 text-sm leading-relaxed">
                Comme <MathComponent math="p" /> est premier, on a <MathComponent math="p \ge 2" />. Il existe donc au moins un élément <MathComponent math="a \in G" /> tel que <MathComponent math="a \neq e" />.
                <br />
                Considérons le sous-groupe engendré par <MathComponent math="a" />, noté <MathComponent math="H = \langle a \rangle = \{a^k, k \in \mathbb{Z}\}" />.
              </p>
            </div>,
            <div className="bg-muted p-4 rounded-xl border border-border">
              <p className="font-bold text-indigo-900 dark:text-indigo-100">Étape 2 : Appliquer le Théorème de Lagrange à H</p>
              <p className="mt-2 text-sm leading-relaxed">
                Par le Théorème de Lagrange, l'ordre de <MathComponent math="H" /> doit diviser l'ordre de <MathComponent math="G" />. On a donc :
                <MathComponent block math="|H| \ \text{divise} \ p" />
                Comme <MathComponent math="p" /> est un nombre premier, ses seuls diviseurs positifs sont <MathComponent math="1" /> et <MathComponent math="p" />. Par conséquent, on a deux choix : soit <MathComponent math="|H| = 1" />, soit <MathComponent math="|H| = p" />.
              </p>
            </div>,
            <div className="bg-emerald-50/50 dark:bg-emerald-900/20 p-4 rounded-xl border border-emerald-100 dark:border-emerald-800/60 font-bold text-emerald-900 dark:text-emerald-100">
              <p>Étape 3 : Écarter le cas trivial</p>
              <p className="mt-2 text-sm leading-relaxed">
                Comme <MathComponent math="a \neq e" />, le sous-groupe <MathComponent math="H" /> contient au moins deux éléments distincts (<MathComponent math="e" /> et <MathComponent math="a" />). Donc, son cardinal <MathComponent math="|H| > 1" />, ce qui exclut <MathComponent math="|H| = 1" />.
                <br />
                La seule possibilité est <MathComponent math="|H| = p = |G|" />.
                Comme <MathComponent math="H" /> est un sous-ensemble de <MathComponent math="G" /> ayant le même cardinal que lui, on en déduit que 
                <MathComponent block math="H = G \implies G = \langle a \rangle" />
                Ainsi, <MathComponent math="G" /> est engendré par un seul élément, ce qui prouve qu'il est cyclique. Tout élément différent de l'élément neutre est un générateur de G.
              </p>
            </div>
          ]}
        />
      </Section>

      <Section title="🗃️ Flashcards de Révision Algébrique" icon="🧠" color="amber">
        <p className="mb-6 text-base text-slate-700 dark:text-slate-300">
          Entraînez-vous à restituer rapidement les notions clés du programme universitaire.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Flashcard 
            front="Qu'est-ce qu'un groupe de Klein ? Donnez son cardinal et structure."
            back="C'est le plus petit groupe non cyclique. Il s'écrit V4 ≅ Z/2Z × Z/2Z. Son cardinal est 4 et chaque élément (hors neutre) est d'ordre 2."
          />
          <Flashcard 
            front="Énoncer le Théorème de Lagrange (cardinalité)."
            back="Si G est un groupe fini et H un sous-groupe de G, alors le cardinal de H divise nécessairement celui de G."
          />
          <Flashcard 
            front="Qu'est-ce qu'un morphisme injectif ? Comment l'identifier ?"
            back="Un morphisme f: G -> G' est injectif si et seulement si son noyau est réduit au neutre : Ker(f) = {e_G}."
          />
        </div>
      </Section>

      <Section title="❓ Foire Aux Questions" icon="💬" color="slate">
        <AccordionFAQ 
          items={[
            {
              question: "Pourquoi l'ensemble Z/nZ est-il si important en algèbre ?",
              answer: "Parce qu'il sert de modèle universel pour tous les groupes cycliques de cardinal fini. Tout groupe cyclique d'ordre n est isomorphe à Z/nZ."
            },
            {
              question: "Quelle est la différence entre sous-groupe et sous-groupe distingué ?",
              answer: "Un sous-groupe H est dit distingué si pour tout x dans G, xH = Hx (les classes à gauche et à droite coïncident). Cette propriété est indispensable pour pouvoir quotienter le groupe G par H et former une nouvelle structure de groupe G/H."
            },
            {
              question: "Qu'est-ce que le cardinal d'un élément d'un groupe ?",
              answer: "On l'appelle plutôt 'l'ordre' d'un élément g. C'est le plus petit entier naturel non nul k tel que g^k = e. Si un tel k n'existe pas, l'élément est dit d'ordre infini."
            }
          ]}
        />
      </Section>

      <Section title="📝 Quiz de Validation" icon="🎓" color="rose">
        <Quiz 
          questions={[
            {
              question: "Si (G, ★) est un groupe et x un élément d'ordre 12, quel est l'ordre du sous-groupe engendré par x^3 ?",
              options: [
                "4",
                "36",
                "3"
              ],
              correctAnswer: 0,
              explanation: "L'ordre de y = x^a dans un groupe cyclique d'ordre k vaut k / pgcd(a, k). Ici, 12 / pgcd(3, 12) = 12 / 3 = 4."
            },
            {
              question: "Quelle est la condition nécessaire pour pouvoir former le groupe quotient G/H ?",
              options: [
                "H doit être d'ordre premier",
                "H doit être un sous-groupe distingué de G",
                "G doit être de cardinal infini"
              ],
              correctAnswer: 1,
              explanation: "H doit impérativement être distingué (ou normal) dans G pour que la loi du quotient soit bien définie indépendamment des représentants de classe."
            },
            {
              question: "Pour un sous-groupe H d'ordre 9 dans un groupe G d'ordre 36. Que vaut l'index [G:H] ?",
              options: [
                "4",
                "3",
                "27"
              ],
              correctAnswer: 0,
              explanation: "D'après le théorème de partitionnement d'index : [G:H] = |G|/|H| = 36/9 = 4."
            },
            {
              question: "Un isomorphisme de groupes est une application...",
              options: [
                "Strictement surjective",
                "Morphismique et bijective",
                "Morphismique et d'image vide"
              ],
              correctAnswer: 1,
              explanation: "Un isomorphisme est défini par un morphisme préservant la structure qui réalise une bijection entre les deux ensembles sous-jacents."
            }
          ]}
        />
        
        <InteractiveChecklist 
          items={[
            "Je sais énoncer et vérifier les axiomes fondamentaux d'un groupe.",
            "Je maîtrise le Théorème de Lagrange et le concept de classes d'équivalences.",
            "Je comprends l'importance d'un sous-groupe distingué pour quotienter.",
            "Je sais tracer une table de Cayley pour étudier les opérations et trouver des inverses."
          ]}
        />
      </Section>

      {!isCompleted && (
        <div className="flex justify-center mt-8">
          <button 
            onClick={onValidateCourse}
            className="flex items-center gap-2 px-8 py-4 bg-emerald-500 hover:bg-emerald-600 text-white rounded-xl shadow-lg shadow-emerald-500/30 transform hover:-translate-y-1 transition-all text-lg font-bold"
          >
            Valider le Chapitre (+30 XP)
          </button>
        </div>
      )}
    </div>
  );
};

export default Course_Licence_Maths_Groupes;
